import imgSlideOne from '@public/img/piano-fingers.jpg';
import imgSlideTwo from '@public/img/movie-camera.jpg';
import imgSlideThree from '@public/img/movie-theater.jpg';
import { TrendingResult, EditorsPick } from './interfacesApp';

export const mockPostsData = [
  {
    postTitle: 'Shaping film through music',
    backgroundImage: imgSlideOne,
    id: 1,
  },
  {
    postTitle: 'Filmmaking equipment for aspiring directors',
    backgroundImage: imgSlideTwo,
    id: 2,
  },
  {
    postTitle: 'How COVID changed movie theater business',
    backgroundImage: imgSlideThree,
    id: 3,
  },
];

export const mockTrendingResults: TrendingResult[] = [
  {
    title: 'Black Panther: Wakanda Forever',
    posterPath: '/sv1xJUazXeYqALzczSZ3O6nkH75.jpg',
  },
  {
    title: 'Black Adam',
    posterPath: '/3zXceNTtyj5FLjwQXuPvLYK5YYL.jpg',
  },
  {
    title: 'Smile',
    posterPath: '/aPqcQwu4VGEewPhagWNncDbJ9Xp.jpg',
  },
  {
    title: 'Enola Holmes 2',
    posterPath: '/tegBpjM5ODoYoM1NjaiHVLEA0QM.jpg',
  },
  {
    title: 'Amsterdam',
    posterPath: '/6sJcVzGCwrDCBMV0DU6eRzA2UxM.jpg',
  },
  {
    title: 'All Quiet on the Western Front',
    posterPath: '/hYqOjJ7Gh1fbqXrxlIao1g8ZehF.jpg',
  },
  {
    title: 'Top Gun: Maverick',
    posterPath: '/62HCnUTziyWcpDaBO2i1DX17ljH.jpg',
  },
  {
    title: 'Star Wars: Andor',
    posterPath: '/59SVNwLfoMnZPPB6ukW6dlPxAdI.jpg',
  },
  {
    title: 'Zootopia+',
    posterPath: '/inzPPPr2BsE92m4rHhQn3sf2yPk.jpg',
  },
];

export const mockTrendingApiData = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: '/bQXAqRx2Fgc46uCVWgoPz5L5Dtr.jpg',
      id: 436270,
      title: 'Black Adam',
      original_language: 'en',
      original_title: 'Black Adam',
      overview:
        'Nearly 5,000 years after he was bestowed with the almighty powers of the Egyptian gods—and imprisoned just as quickly—Black Adam is freed from his earthly tomb, ready to unleash his unique form of justice on the modern world.',
      poster_path: '/pFlaoHTZeyNkG83vxsAJiGzfSsa.jpg',
      media_type: 'movie',
      genre_ids: [28, 14, 878],
      popularity: 11801.698,
      release_date: '2022-10-19',
      video: false,
      vote_average: 7.284,
      vote_count: 2209,
    },
    {
      adult: false,
      backdrop_path: '/rfnmMYuZ6EKOBvQLp2wqP21v7sI.jpg',
      id: 774752,
      title: 'The Guardians of the Galaxy Holiday Special',
      original_language: 'en',
      original_title: 'The Guardians of the Galaxy Holiday Special',
      overview:
        'On a mission to make Christmas unforgettable for Quill, the Guardians head to Earth in search of the perfect present.',
      poster_path: '/8dqXyslZ2hv49Oiob9UjlGSHSTR.jpg',
      media_type: 'movie',
      genre_ids: [35, 878, 12],
      popularity: 755.423,
      release_date: '2022-11-25',
      video: false,
      vote_average: 7.475,
      vote_count: 417,
    },
    {
      adult: false,
      backdrop_path: '/9DpB6wC1iY5jxLz91RT8tIIsXaf.jpg',
      id: 119051,
      name: 'Wednesday',
      original_language: 'en',
      original_name: 'Wednesday',
      overview:
        'Wednesday Addams is sent to Nevermore Academy, a bizarre boarding school where she attempts to master her psychic powers, stop a monstrous killing spree of the town citizens, and solve the supernatural mystery that affected her family 25 years ago — all while navigating her new relationships.',
      poster_path: '/jeGtaMwGxPmQN5xM4ClnwPQcNQz.jpg',
      media_type: 'tv',
      genre_ids: [10765, 9648, 35],
      popularity: 2738.723,
      first_air_date: '2022-11-23',
      vote_average: 8.784,
      vote_count: 1088,
      origin_country: ['US'],
    },
    {
      adult: false,
      backdrop_path: '/xDMIl84Qo5Tsu62c9DGWhmPI67A.jpg',
      id: 505642,
      title: 'Black Panther: Wakanda Forever',
      original_language: 'en',
      original_title: 'Black Panther: Wakanda Forever',
      overview:
        'Queen Ramonda, Shuri, M’Baku, Okoye and the Dora Milaje fight to protect their nation from intervening world powers in the wake of King T’Challa’s death. As the Wakandans strive to embrace their next chapter, the heroes must band together with the help of War Dog Nakia and Everett Ross and forge a new path for the kingdom of Wakanda.',
      poster_path: '/ps2oKfhY6DL3alynlSqY97gHSsg.jpg',
      media_type: 'movie',
      genre_ids: [28, 12, 878],
      popularity: 1809.575,
      release_date: '2022-11-09',
      video: false,
      vote_average: 7.529,
      vote_count: 1101,
    },
    {
      adult: false,
      backdrop_path: '/s1xnjbOIQtwGObPnydTebp74G2c.jpg',
      id: 90669,
      name: '1899',
      original_language: 'zh',
      original_name: '1899',
      overview:
        'Passengers on an immigrant ship traveling to the new continent get caught in a mysterious riddle when they find a second vessel adrift on the open sea.',
      poster_path: '/8KGvYHQNOamON6ufQGjyhkiVn1V.jpg',
      media_type: 'tv',
      genre_ids: [9648, 18],
      popularity: 1910.521,
      first_air_date: '2022-11-17',
      vote_average: 7.899,
      vote_count: 357,
      origin_country: ['DE'],
    },
    {
      adult: false,
      backdrop_path: '/o3mothJXDR9vLlZHpwyfFCycCNx.jpg',
      id: 668461,
      title: 'Slumberland',
      original_language: 'en',
      original_title: 'Slumberland',
      overview:
        'A young girl discovers a secret map to the dreamworld of Slumberland, and with the help of an eccentric outlaw, she traverses dreams and flees nightmares, with the hope that she will be able to see her late father again.',
      poster_path: '/f18kgonrgr8YvEuvshExS4XBGL8.jpg',
      media_type: 'movie',
      genre_ids: [10751, 14, 12, 18],
      popularity: 1136.271,
      release_date: '2022-11-09',
      video: false,
      vote_average: 7.865,
      vote_count: 292,
    },
    {
      adult: false,
      backdrop_path: '/ajztm40qDPqMONaSJhQ2PaNe2Xd.jpg',
      id: 83867,
      name: 'Star Wars: Andor',
      original_language: 'en',
      original_name: 'Star Wars: Andor',
      overview:
        'The tale of the burgeoning rebellion against the Empire and how people and planets became involved. In an era filled with danger, deception and intrigue, Cassian Andor embarks on the path that is destined to turn him into a rebel hero.',
      poster_path: '/59SVNwLfoMnZPPB6ukW6dlPxAdI.jpg',
      media_type: 'tv',
      genre_ids: [10765, 10759, 10768],
      popularity: 588.674,
      first_air_date: '2022-09-21',
      vote_average: 8.155,
      vote_count: 364,
      origin_country: ['US'],
    },
    {
      adult: false,
      backdrop_path: '/fHDvGGPFry65ou79WLi6JsjCZrM.jpg',
      id: 632856,
      title: 'Spirited',
      original_language: 'en',
      original_title: 'Spirited',
      overview:
        'Each Christmas Eve, the Ghost of Christmas Present selects one dark soul to be reformed by a visit from three spirits. But this season, he picked the wrong Scrooge. Clint Briggs turns the tables on his ghostly host until Present finds himself reexamining his own past, present and future.',
      poster_path: '/h3zAzTMs5EP3cKusOxFNGSFE1WI.jpg',
      media_type: 'movie',
      genre_ids: [35],
      popularity: 489.931,
      release_date: '2022-11-10',
      video: false,
      vote_average: 7.307,
      vote_count: 161,
    },
    {
      adult: false,
      backdrop_path: '/c1bz69r0v065TGFA5nqBiKzPDys.jpg',
      id: 830784,
      title: 'Lyle, Lyle, Crocodile',
      original_language: 'en',
      original_title: 'Lyle, Lyle, Crocodile',
      overview:
        'When the Primm family moves to New York City, their young son Josh struggles to adapt to his new school and new friends. All of that changes when he discovers Lyle — a singing crocodile who loves baths, caviar and great music — living in the attic of his new home. But when Lyle’s existence is threatened by evil neighbor Mr. Grumps, the Primms must band together to show the world that family can come from the most unexpected places.',
      poster_path: '/irIS5Tn3TXjNi1R9BpWvGAN4CZ1.jpg',
      media_type: 'movie',
      genre_ids: [35, 10751, 10402],
      popularity: 1936.367,
      release_date: '2022-10-07',
      video: false,
      vote_average: 7.661,
      vote_count: 93,
    },
    {
      adult: false,
      backdrop_path: '/kpUre8wWSXn3D5RhrMttBZa6w1v.jpg',
      id: 338958,
      title: 'Disenchanted',
      original_language: 'en',
      original_title: 'Disenchanted',
      overview:
        'Disillusioned with life in the city, feeling out of place in suburbia, and frustrated that her happily ever after hasn’t been so easy to find, Giselle turns to the magic of Andalasia for help. Accidentally transforming the entire town into a real-life fairy tale and placing her family’s future happiness in jeopardy, she must race against time to reverse the spell and determine what happily ever after truly means to her and her family.',
      poster_path: '/4x3pt6hoLblBeHebUa4OyiVXFiM.jpg',
      media_type: 'movie',
      genre_ids: [35, 10751, 14],
      popularity: 1969.641,
      release_date: '2022-11-16',
      video: false,
      vote_average: 7.326,
      vote_count: 429,
    },
    {
      adult: false,
      backdrop_path: '/olPXihyFeeNvnaD6IOBltgIV1FU.jpg',
      id: 882598,
      title: 'Smile',
      original_language: 'en',
      original_title: 'Smile',
      overview:
        "After witnessing a bizarre, traumatic incident involving a patient, Dr. Rose Cotter starts experiencing frightening occurrences that she can't explain. As an overwhelming terror begins taking over her life, Rose must confront her troubling past in order to survive and escape her horrifying new reality.",
      poster_path: '/aPqcQwu4VGEewPhagWNncDbJ9Xp.jpg',
      media_type: 'movie',
      genre_ids: [27, 9648, 53],
      popularity: 1479.33,
      release_date: '2022-09-23',
      video: false,
      vote_average: 6.804,
      vote_count: 975,
    },
    {
      adult: false,
      backdrop_path: '/7zQJYV02yehWrQN6NjKsBorqUUS.jpg',
      id: 724495,
      title: 'The Woman King',
      original_language: 'en',
      original_title: 'The Woman King',
      overview:
        'The story of the Agojie, the all-female unit of warriors who protected the African Kingdom of Dahomey in the 1800s with skills and a fierceness unlike anything the world has ever seen, and General Nanisca as she trains the next generation of recruits and readies them for battle against an enemy determined to destroy their way of life.',
      poster_path: '/438QXt1E3WJWb3PqNniK0tAE5c1.jpg',
      media_type: 'movie',
      genre_ids: [28, 18, 36],
      popularity: 4376.054,
      release_date: '2022-09-15',
      video: false,
      vote_average: 7.889,
      vote_count: 534,
    },
    {
      adult: false,
      backdrop_path: '/93SxdkiR3gBcbG5FxIt0DCBttul.jpg',
      id: 111837,
      name: 'Willow',
      original_language: 'en',
      original_name: 'Willow',
      overview:
        'Many years after the events of the original film, legendary sorcerer Willow leads a group of misfit heroes on a dangerous rescue mission through a world beyond their wildest imaginations.',
      poster_path: '/jhdSPDlhswjN1r6O0pGP3ZvQgU8.jpg',
      media_type: 'tv',
      genre_ids: [10765, 10759, 18],
      popularity: 101.781,
      first_air_date: '2022-11-30',
      vote_average: 6.714,
      vote_count: 15,
      origin_country: ['US'],
    },
    {
      adult: false,
      backdrop_path: '/198vrF8k7mfQ4FjDJsBmdQcaiyq.jpg',
      id: 76600,
      title: 'Avatar: The Way of Water',
      original_language: 'en',
      original_title: 'Avatar: The Way of Water',
      overview:
        'Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.',
      poster_path: '/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg',
      media_type: 'movie',
      genre_ids: [878, 28, 12],
      popularity: 624.738,
      release_date: '2022-12-14',
      video: false,
      vote_average: 0.0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: '/AaV1YIdWKnjAIAOe8UUKBFm327v.jpg',
      id: 361743,
      title: 'Top Gun: Maverick',
      original_language: 'en',
      original_title: 'Top Gun: Maverick',
      overview:
        'After more than thirty years of service as one of the Navy’s top aviators, and dodging the advancement in rank that would ground him, Pete “Maverick” Mitchell finds himself training a detachment of TOP GUN graduates for a specialized mission the likes of which no living pilot has ever seen.',
      poster_path: '/62HCnUTziyWcpDaBO2i1DX17ljH.jpg',
      media_type: 'movie',
      genre_ids: [28, 18],
      popularity: 466.17,
      release_date: '2022-05-24',
      video: false,
      vote_average: 8.346,
      vote_count: 4873,
    },
    {
      adult: false,
      backdrop_path: '/zaulpwl355dlKkvtAiSBE5LaoWA.jpg',
      id: 1402,
      name: 'The Walking Dead',
      original_language: 'en',
      original_name: 'The Walking Dead',
      overview:
        "Sheriff's deputy Rick Grimes awakens from a coma to find a post-apocalyptic world dominated by flesh-eating zombies. He sets out to find his family and encounters many other survivors along the way.",
      poster_path: '/xf9wuDcqlUPWABZNeDKPbZUjWx0.jpg',
      media_type: 'tv',
      genre_ids: [10759, 18, 10765],
      popularity: 859.331,
      first_air_date: '2010-10-31',
      vote_average: 8.111,
      vote_count: 14135,
      origin_country: ['US'],
    },
    {
      adult: false,
      backdrop_path: '/79PcXPpbDWql74h8Y00mNwbYMbS.jpg',
      id: 664469,
      title: 'Amsterdam',
      original_language: 'en',
      original_title: 'Amsterdam',
      overview:
        'In the 1930s, three friends—a doctor, a nurse, and an attorney—witness a murder, become suspects themselves and uncover one of the most outrageous plots in North American history.',
      poster_path: '/6sJcVzGCwrDCBMV0DU6eRzA2UxM.jpg',
      media_type: 'movie',
      genre_ids: [80, 35, 36, 9648, 53],
      popularity: 182.222,
      release_date: '2022-09-27',
      video: false,
      vote_average: 6.136,
      vote_count: 389,
    },
    {
      adult: false,
      backdrop_path: '/tP5PwKwDxnFu6FpM2hOWyqjf6Qy.jpg',
      id: 823766,
      title: 'The Wonder',
      original_language: 'en',
      original_title: 'The Wonder',
      overview:
        "Haunted by her past, a nurse travels from England to a remote Irish village in 1862 to investigate a young girl's supposedly miraculous fast.",
      poster_path: '/7IBBCGAyvakb36B3Rz8Fyk1V1Wg.jpg',
      media_type: 'movie',
      genre_ids: [9648, 53, 18],
      popularity: 151.383,
      release_date: '2022-11-02',
      video: false,
      vote_average: 6.755,
      vote_count: 247,
    },
    {
      adult: false,
      backdrop_path: '/hIZFG7MK4leU4axRFKJWqrjhmxZ.jpg',
      id: 95403,
      name: 'The Peripheral',
      original_language: 'en',
      original_name: 'The Peripheral',
      overview:
        'Stuck in a small Appalachian town, a young woman’s only escape from the daily grind is playing advanced video games. She is such a good player that a company sends her a new video game system to test…but it has a surprise in store. It unlocks all of her dreams of finding a purpose, romance, and glamour in what seems like a game…but it also puts her and her family in real danger.',
      poster_path: '/ccBe5BVeibdBEQU7l6P6BubajWV.jpg',
      media_type: 'tv',
      genre_ids: [10765, 18],
      popularity: 1756.917,
      first_air_date: '2022-10-20',
      vote_average: 8.207,
      vote_count: 309,
      origin_country: ['US'],
    },
    {
      adult: false,
      backdrop_path: '/rjlG7C5GZfXutoVoE3BJaYGUhk4.jpg',
      id: 829280,
      title: 'Enola Holmes 2',
      original_language: 'en',
      original_title: 'Enola Holmes 2',
      overview:
        'Now a detective-for-hire like her infamous brother, Enola Holmes takes on her first official case to find a missing girl, as the sparks of a dangerous conspiracy ignite a mystery that requires the help of friends — and Sherlock himself — to unravel.',
      poster_path: '/tegBpjM5ODoYoM1NjaiHVLEA0QM.jpg',
      media_type: 'movie',
      genre_ids: [9648, 12, 35, 80],
      popularity: 1017.379,
      release_date: '2022-11-04',
      video: false,
      vote_average: 7.739,
      vote_count: 1189,
    },
  ],
  total_pages: 1000,
  total_results: 20000,
};

export const mockEditorsPicks: EditorsPick[] = [
  {
    title: 'Good Bye Lenin!',
    posterPath: '/2xv7MuQFxJMK1ZV0r5fFI0FzdG0.jpg',
    year: '2003',
    id: 338,
  },
  {
    title: 'La La Land',
    posterPath: '/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg',
    year: '2016',
    id: 313369,
  },
  {
    title: 'Rush',
    posterPath: '/5akKFgS7eeXUw9rKTEujryKrH17.jpg',
    year: '2013',
    id: 96721,
  },
  {
    title: '2001: A Space Odyssey',
    posterPath: '/ve72VxNqjGM69Uky4WTo2bK6rfq.jpg',
    year: '1973',
    id: 62,
  },
];

export const mockMovieContentSummary = {
  contentInfo: {
    adult: false,
    backdrop_path: '/kCEXA22ASuq7Y29jnngyaisyA0X.jpg',
    belongs_to_collection: {
      id: 4438,
      name: 'The Space Odyssey Series',
      poster_path: '/bxQaNDuSLCllnMSQ0ZLg7e6HrMW.jpg',
      backdrop_path: '/15FumSExI9SRoL7QJWZAsA0b10c.jpg',
    },
    budget: 12000000,
    genres: [
      {
        id: 878,
        name: 'Science Fiction',
      },
      {
        id: 9648,
        name: 'Mystery',
      },
      {
        id: 12,
        name: 'Adventure',
      },
    ],
    homepage: 'http://2001spaceodysseymovie.com',
    id: 62,
    imdb_id: 'tt0062622',
    original_language: 'en',
    original_title: '2001: A Space Odyssey',
    overview:
      "Humanity finds a mysterious object buried beneath the lunar surface and sets off to find its origins with the help of HAL 9000, the world's most advanced super computer.",
    popularity: 48.382,
    poster_path: '/ve72VxNqjGM69Uky4WTo2bK6rfq.jpg',
    production_companies: [
      {
        id: 385,
        logo_path: null,
        name: 'Stanley Kubrick Productions',
        origin_country: 'GB',
      },
      {
        id: 21,
        logo_path: '/aOWKh4gkNrfFZ3Ep7n0ckPhoGb5.png',
        name: 'Metro-Goldwyn-Mayer',
        origin_country: 'US',
      },
    ],
    production_countries: [
      {
        iso_3166_1: 'GB',
        name: 'United Kingdom',
      },
      {
        iso_3166_1: 'US',
        name: 'United States of America',
      },
    ],
    release_date: '1968-04-02',
    revenue: 71923560,
    runtime: 149,
    spoken_languages: [
      {
        english_name: 'English',
        iso_639_1: 'en',
        name: 'English',
      },
      {
        english_name: 'Russian',
        iso_639_1: 'ru',
        name: 'Pусский',
      },
    ],
    status: 'Released',
    tagline: 'The Ultimate Trip.',
    title: '2001: A Space Odyssey',
    video: false,
    vote_average: 8.083,
    vote_count: 10038,
  },
  credits: {
    id: 62,
    cast: [
      {
        adult: false,
        gender: 2,
        id: 245,
        known_for_department: 'Acting',
        name: 'Keir Dullea',
        original_name: 'Keir Dullea',
        popularity: 11.773,
        profile_path: '/dL9i0nCk2fCgInZNaYVjGck2IBp.jpg',
        cast_id: 6,
        character: 'Dr. David Bowman',
        credit_id: '52fe4212c3a36847f8001a1b',
        order: 0,
      },
      {
        adult: false,
        gender: 2,
        id: 246,
        known_for_department: 'Acting',
        name: 'Gary Lockwood',
        original_name: 'Gary Lockwood',
        popularity: 3.279,
        profile_path: '/lQBqZKpMxGslopZRvFanIWL4pSl.jpg',
        cast_id: 7,
        character: 'Dr. Frank Poole',
        credit_id: '52fe4212c3a36847f8001a1f',
        order: 1,
      },
      {
        adult: false,
        gender: 2,
        id: 247,
        known_for_department: 'Acting',
        name: 'William Sylvester',
        original_name: 'William Sylvester',
        popularity: 2.785,
        profile_path: '/uTBTJscyXqvDWpv17QyT4VVDAJn.jpg',
        cast_id: 8,
        character: 'Dr. Heywood Floyd',
        credit_id: '52fe4212c3a36847f8001a23',
        order: 2,
      },
      {
        adult: false,
        gender: 2,
        id: 253,
        known_for_department: 'Acting',
        name: 'Douglas Rain',
        original_name: 'Douglas Rain',
        popularity: 3.504,
        profile_path: '/blDCxSTUP5U9EdKOmhGtRvhby2c.jpg',
        cast_id: 14,
        character: 'HAL 9000 (voice)',
        credit_id: '52fe4212c3a36847f8001a3b',
        order: 3,
      },
      {
        adult: false,
        gender: 2,
        id: 248,
        known_for_department: 'Acting',
        name: 'Daniel Richter',
        original_name: 'Daniel Richter',
        popularity: 1.028,
        profile_path: '/cq8Fprv33RgYPwu39cGx6fxk5Qp.jpg',
        cast_id: 9,
        character: 'Moonwatcher',
        credit_id: '52fe4212c3a36847f8001a27',
        order: 4,
      },
      {
        adult: false,
        gender: 2,
        id: 249,
        known_for_department: 'Acting',
        name: 'Leonard Rossiter',
        original_name: 'Leonard Rossiter',
        popularity: 3.703,
        profile_path: '/qXjGUJ2TjO3ltiEYMEJ658VeqkA.jpg',
        cast_id: 10,
        character: 'Dr. Andrei Smyslov',
        credit_id: '52fe4212c3a36847f8001a2b',
        order: 5,
      },
      {
        adult: false,
        gender: 1,
        id: 250,
        known_for_department: 'Acting',
        name: 'Margaret Tyzack',
        original_name: 'Margaret Tyzack',
        popularity: 2.814,
        profile_path: '/n7S4qtgp0DA9gtkzEXB7r5tt6jH.jpg',
        cast_id: 11,
        character: 'Elena',
        credit_id: '52fe4212c3a36847f8001a2f',
        order: 6,
      },
      {
        adult: false,
        gender: 2,
        id: 251,
        known_for_department: 'Acting',
        name: 'Robert Beatty',
        original_name: 'Robert Beatty',
        popularity: 5.474,
        profile_path: '/ihB3jLo9i4p6wR6xJXjor9mav7W.jpg',
        cast_id: 12,
        character: 'Dr. Ralph Halvorsen',
        credit_id: '52fe4212c3a36847f8001a33',
        order: 7,
      },
      {
        adult: false,
        gender: 2,
        id: 252,
        known_for_department: 'Acting',
        name: 'Sean Sullivan',
        original_name: 'Sean Sullivan',
        popularity: 1.138,
        profile_path: '/o9B11WVoEzNmGQjYHWSWZKMCaAH.jpg',
        cast_id: 13,
        character: 'Dr. Roy Michaels',
        credit_id: '52fe4212c3a36847f8001a37',
        order: 8,
      },
      {
        adult: false,
        gender: 2,
        id: 102573,
        known_for_department: 'Acting',
        name: 'Frank Miller',
        original_name: 'Frank Miller',
        popularity: 0.6,
        profile_path: null,
        cast_id: 30,
        character: 'Mission Controller',
        credit_id: '52fe4212c3a36847f8001a83',
        order: 9,
      },
      {
        adult: false,
        gender: 2,
        id: 108277,
        known_for_department: 'Acting',
        name: 'Ed Bishop',
        original_name: 'Ed Bishop',
        popularity: 3.332,
        profile_path: '/uLLoKf4BknxuF1SOSD0EBB4gSmc.jpg',
        cast_id: 25,
        character: 'Aries-1B Lunar Shuttle Captain',
        credit_id: '52fe4212c3a36847f8001a73',
        order: 10,
      },
      {
        adult: false,
        gender: 1,
        id: 117540,
        known_for_department: 'Acting',
        name: 'Edwina Carroll',
        original_name: 'Edwina Carroll',
        popularity: 0.805,
        profile_path: '/1cnJio9ZtRXFUKIB0NiSIpb1lNI.jpg',
        cast_id: 29,
        character: 'Aries-1B Stewardess',
        credit_id: '52fe4212c3a36847f8001a7f',
        order: 11,
      },
      {
        adult: false,
        gender: 1,
        id: 1102076,
        known_for_department: 'Acting',
        name: 'Heather Downham',
        original_name: 'Heather Downham',
        popularity: 1.4,
        profile_path: null,
        cast_id: 40,
        character: 'Stewardess',
        credit_id: '539d3d76c3a3683b50002997',
        order: 12,
      },
      {
        adult: false,
        gender: 1,
        id: 127363,
        known_for_department: 'Acting',
        name: 'Penny Brahms',
        original_name: 'Penny Brahms',
        popularity: 3.443,
        profile_path: '/uFjTuQ02DL7fHF4FpazTkA9q0W1.jpg',
        cast_id: 39,
        character: 'Stewardess',
        credit_id: '539d3d53c3a3683b2a002a98',
        order: 13,
      },
      {
        adult: false,
        gender: 1,
        id: 1819434,
        known_for_department: 'Acting',
        name: 'Maggie London',
        original_name: 'Maggie London',
        popularity: 0.997,
        profile_path: '/nnKmKldpUAjGsrkm7TFd55UxqrN.jpg',
        cast_id: 82,
        character: 'Stewardess',
        credit_id: '591e5bccc3a3687a8e028c10',
        order: 14,
      },
      {
        adult: false,
        gender: 1,
        id: 1819435,
        known_for_department: 'Acting',
        name: 'Chela Matthison',
        original_name: 'Chela Matthison',
        popularity: 0.6,
        profile_path: '/oFVJX9OnmOhXoMDvLf4V9dQtUxx.jpg',
        cast_id: 83,
        character: 'Stewardess',
        credit_id: '591e5be29251414add0291a1',
        order: 15,
      },
      {
        adult: false,
        gender: 0,
        id: 1819436,
        known_for_department: 'Acting',
        name: 'Judy Kiern',
        original_name: 'Judy Kiern',
        popularity: 0.6,
        profile_path: null,
        cast_id: 84,
        character: 'Voiceprint Identification Girl',
        credit_id: '591e5bfac3a3687912026cc5',
        order: 16,
      },
      {
        adult: false,
        gender: 2,
        id: 93948,
        known_for_department: 'Acting',
        name: 'Alan Gifford',
        original_name: 'Alan Gifford',
        popularity: 0.746,
        profile_path: '/dnj49L9ktGVOfBqqtIvpDd0ALba.jpg',
        cast_id: 27,
        character: "Poole's Father",
        credit_id: '52fe4212c3a36847f8001a77',
        order: 17,
      },
      {
        adult: false,
        gender: 1,
        id: 107445,
        known_for_department: 'Acting',
        name: 'Ann Gillis',
        original_name: 'Ann Gillis',
        popularity: 0.6,
        profile_path: '/vFaBH7EuS8hEOO4R76V5Tm2aRG9.jpg',
        cast_id: 28,
        character: "Poole's Mother",
        credit_id: '52fe4212c3a36847f8001a7b',
        order: 18,
      },
      {
        adult: false,
        gender: 1,
        id: 8645,
        known_for_department: 'Acting',
        name: 'Vivian Kubrick',
        original_name: 'Vivian Kubrick',
        popularity: 1.555,
        profile_path: '/abkr2zJWKURpfzsBJDGeYZZaAXt.jpg',
        cast_id: 70,
        character: "Floyd's daughter (uncredited)",
        credit_id: '539d41d2c3a3683b41002bee',
        order: 19,
      },
      {
        adult: false,
        gender: 2,
        id: 1330813,
        known_for_department: 'Acting',
        name: 'Kenneth Kendall',
        original_name: 'Kenneth Kendall',
        popularity: 0.983,
        profile_path: '/d17VpNCQBuwMIdQvpZuA0TLsmJu.jpg',
        cast_id: 69,
        character: 'BBC-12 Announcer',
        credit_id: '539d41b9c3a3683b50002b1f',
        order: 20,
      },
      {
        adult: false,
        gender: 2,
        id: 1330820,
        known_for_department: 'Acting',
        name: 'Kevin Scott',
        original_name: 'Kevin Scott',
        popularity: 0.6,
        profile_path: '/3ZrUmuJBv8PHoC5AjcpC5zjKjMa.jpg',
        cast_id: 77,
        character: 'Miller',
        credit_id: '539d427dc3a3683b23002d36',
        order: 21,
      },
      {
        adult: false,
        gender: 0,
        id: 1330806,
        known_for_department: 'Acting',
        name: 'Martin Amor',
        original_name: 'Martin Amor',
        popularity: 0.6,
        profile_path: null,
        cast_id: 62,
        character: 'Interviewer Martin Amor',
        credit_id: '539d4069c3a3683b48002a28',
        order: 22,
      },
      {
        adult: false,
        gender: 2,
        id: 24278,
        known_for_department: 'Acting',
        name: 'Bill Weston',
        original_name: 'Bill Weston',
        popularity: 3.77,
        profile_path: '/mQtWjSvfDlgI42NrE5E3nfICGbE.jpg',
        cast_id: 24,
        character: 'Astronaut',
        credit_id: '52fe4212c3a36847f8001a6f',
        order: 23,
      },
      {
        adult: false,
        gender: 2,
        id: 948173,
        known_for_department: 'Acting',
        name: 'Glenn Beck',
        original_name: 'Glenn Beck',
        popularity: 2.618,
        profile_path: '/9QeeMaBYTPSQYxm6GlMSuowu3GE.jpg',
        cast_id: 31,
        character: 'Astronaut',
        credit_id: '52fe4212c3a36847f8001a87',
        order: 24,
      },
      {
        adult: false,
        gender: 0,
        id: 1330785,
        known_for_department: 'Acting',
        name: 'Mike Lovell',
        original_name: 'Mike Lovell',
        popularity: 0.6,
        profile_path: null,
        cast_id: 41,
        character: 'Astronaut',
        credit_id: '539d3da9c3a3683b500029a3',
        order: 25,
      },
      {
        adult: false,
        gender: 0,
        id: 1330786,
        known_for_department: 'Acting',
        name: 'John Ashley',
        original_name: 'John Ashley',
        popularity: 0.6,
        profile_path: null,
        cast_id: 42,
        character: 'Ape',
        credit_id: '539d3df0c3a3683b37002a8b',
        order: 26,
      },
      {
        adult: false,
        gender: 0,
        id: 1330787,
        known_for_department: 'Acting',
        name: 'Jimmy Bell',
        original_name: 'Jimmy Bell',
        popularity: 0.6,
        profile_path: null,
        cast_id: 43,
        character: 'Ape',
        credit_id: '539d3e13c3a3683b37002a92',
        order: 27,
      },
      {
        adult: false,
        gender: 2,
        id: 1330788,
        known_for_department: 'Acting',
        name: 'David Charkham',
        original_name: 'David Charkham',
        popularity: 1.214,
        profile_path: '/9ehZ0SGVmD6JIqpFIlzhlemfBrK.jpg',
        cast_id: 44,
        character: 'Ape',
        credit_id: '539d3e2ec3a3683b590029db',
        order: 28,
      },
      {
        adult: false,
        gender: 0,
        id: 1330789,
        known_for_department: 'Acting',
        name: 'Simon Davis',
        original_name: 'Simon Davis',
        popularity: 0.6,
        profile_path: null,
        cast_id: 45,
        character: 'Ape',
        credit_id: '539d3e44c3a3683b41002a7e',
        order: 29,
      },
      {
        adult: false,
        gender: 0,
        id: 1330790,
        known_for_department: 'Acting',
        name: 'Jonathan Daw',
        original_name: 'Jonathan Daw',
        popularity: 0.6,
        profile_path: null,
        cast_id: 46,
        character: 'Ape',
        credit_id: '539d3e6ac3a3683b23002b57',
        order: 30,
      },
      {
        adult: false,
        gender: 0,
        id: 1330791,
        known_for_department: 'Acting',
        name: 'Péter Delmár',
        original_name: 'Péter Delmár',
        popularity: 0.6,
        profile_path: null,
        cast_id: 47,
        character: 'Ape',
        credit_id: '539d3e80c3a3683b310029ff',
        order: 31,
      },
      {
        adult: false,
        gender: 2,
        id: 1214098,
        known_for_department: 'Acting',
        name: 'Terry Duggan',
        original_name: 'Terry Duggan',
        popularity: 0.98,
        profile_path: null,
        cast_id: 48,
        character: 'Ape Attacked by Leopard',
        credit_id: '539d3ec4c3a3683b23002b81',
        order: 32,
      },
      {
        adult: false,
        gender: 0,
        id: 1330793,
        known_for_department: 'Acting',
        name: 'David Fleetwood',
        original_name: 'David Fleetwood',
        popularity: 0.6,
        profile_path: null,
        cast_id: 49,
        character: 'Ape',
        credit_id: '539d3eeac3a3683b23002b88',
        order: 33,
      },
      {
        adult: false,
        gender: 0,
        id: 1330794,
        known_for_department: 'Acting',
        name: 'Danny Grover',
        original_name: 'Danny Grover',
        popularity: 0.6,
        profile_path: null,
        cast_id: 50,
        character: 'Ape',
        credit_id: '539d3f04c3a3683b2a002ad4',
        order: 34,
      },
      {
        adult: false,
        gender: 0,
        id: 1330795,
        known_for_department: 'Acting',
        name: 'Brian Hawley',
        original_name: 'Brian Hawley',
        popularity: 0.6,
        profile_path: null,
        cast_id: 51,
        character: 'Ape',
        credit_id: '539d3f25c3a3683b23002ba3',
        order: 35,
      },
      {
        adult: false,
        gender: 0,
        id: 1330796,
        known_for_department: 'Acting',
        name: 'David Hines',
        original_name: 'David Hines',
        popularity: 0.6,
        profile_path: null,
        cast_id: 52,
        character: 'Ape',
        credit_id: '539d3f42c3a3683b50002a01',
        order: 36,
      },
      {
        adult: false,
        gender: 0,
        id: 1330797,
        known_for_department: 'Acting',
        name: 'Tony Jackson',
        original_name: 'Tony Jackson',
        popularity: 0.6,
        profile_path: null,
        cast_id: 53,
        character: 'Ape',
        credit_id: '539d3f81c3a3683b50002a27',
        order: 37,
      },
      {
        adult: false,
        gender: 0,
        id: 1330798,
        known_for_department: 'Acting',
        name: 'John Jordan',
        original_name: 'John Jordan',
        popularity: 0.6,
        profile_path: null,
        cast_id: 54,
        character: 'Ape',
        credit_id: '539d3f9ec3a3683b31002a89',
        order: 38,
      },
      {
        adult: false,
        gender: 0,
        id: 1330799,
        known_for_department: 'Acting',
        name: 'Scott MacKee',
        original_name: 'Scott MacKee',
        popularity: 0.6,
        profile_path: null,
        cast_id: 55,
        character: 'Ape',
        credit_id: '539d3fb4c3a3683b41002b14',
        order: 39,
      },
      {
        adult: false,
        gender: 0,
        id: 1330800,
        known_for_department: 'Acting',
        name: 'Laurence Marchant',
        original_name: 'Laurence Marchant',
        popularity: 0.6,
        profile_path: null,
        cast_id: 56,
        character: 'Ape',
        credit_id: '539d3fcbc3a3683b59002a74',
        order: 40,
      },
      {
        adult: false,
        gender: 0,
        id: 1330801,
        known_for_department: 'Acting',
        name: 'Darryl Paes',
        original_name: 'Darryl Paes',
        popularity: 0.6,
        profile_path: null,
        cast_id: 57,
        character: 'Ape',
        credit_id: '539d3fe5c3a3683b31002ab7',
        order: 41,
      },
      {
        adult: false,
        gender: 0,
        id: 1330802,
        known_for_department: 'Acting',
        name: 'Joe Refalo',
        original_name: 'Joe Refalo',
        popularity: 0.6,
        profile_path: null,
        cast_id: 58,
        character: 'Ape',
        credit_id: '539d3fffc3a3683b50002a65',
        order: 42,
      },
      {
        adult: false,
        gender: 0,
        id: 1330803,
        known_for_department: 'Acting',
        name: 'Andy Wallace',
        original_name: 'Andy Wallace',
        popularity: 0.6,
        profile_path: null,
        cast_id: 59,
        character: 'Ape',
        credit_id: '539d4011c3a3683b48002a0b',
        order: 43,
      },
      {
        adult: false,
        gender: 0,
        id: 1330804,
        known_for_department: 'Acting',
        name: 'Bob Wilyman',
        original_name: 'Bob Wilyman',
        popularity: 0.6,
        profile_path: null,
        cast_id: 60,
        character: 'Ape',
        credit_id: '539d4024c3a3683b23002c27',
        order: 44,
      },
      {
        adult: false,
        gender: 0,
        id: 1330805,
        known_for_department: 'Acting',
        name: 'Richard Woods',
        original_name: 'Richard Woods',
        popularity: 0.6,
        profile_path: null,
        cast_id: 61,
        character: 'Ape Killed by Moon-Watcher',
        credit_id: '539d4048c3a3683b50002a82',
        order: 45,
      },
      {
        adult: false,
        gender: 0,
        id: 1330807,
        known_for_department: 'Acting',
        name: 'S. Newton Anderson',
        original_name: 'S. Newton Anderson',
        popularity: 0.6,
        profile_path: null,
        cast_id: 63,
        character: 'Young Man (uncredited)',
        credit_id: '539d407ec3a3683b41002b55',
        order: 46,
      },
      {
        adult: false,
        gender: 0,
        id: 1330808,
        known_for_department: 'Acting',
        name: 'Sheraton Blount',
        original_name: 'Sheraton Blount',
        popularity: 0.6,
        profile_path: null,
        cast_id: 64,
        character: '(uncredited)',
        credit_id: '539d4092c3a3683b50002a8b',
        order: 47,
      },
      {
        adult: false,
        gender: 0,
        id: 1330809,
        known_for_department: 'Acting',
        name: 'Ann Bormann',
        original_name: 'Ann Bormann',
        popularity: 0.6,
        profile_path: null,
        cast_id: 65,
        character: '(uncredited)',
        credit_id: '539d40a6c3a3683b41002b5c',
        order: 48,
      },
      {
        adult: false,
        gender: 1,
        id: 1330811,
        known_for_department: 'Acting',
        name: 'Julie Croft',
        original_name: 'Julie Croft',
        popularity: 0.6,
        profile_path: null,
        cast_id: 67,
        character: '(uncredited)',
        credit_id: '539d4177c3a3683b48002a75',
        order: 49,
      },
      {
        adult: false,
        gender: 1,
        id: 1330812,
        known_for_department: 'Acting',
        name: 'Penny Francis',
        original_name: 'Penny Francis',
        popularity: 0.6,
        profile_path: null,
        cast_id: 68,
        character: '(uncredited)',
        credit_id: '539d418fc3a3683b41002baf',
        order: 50,
      },
      {
        adult: false,
        gender: 1,
        id: 1330814,
        known_for_department: 'Acting',
        name: 'Marcella Markham',
        original_name: 'Marcella Markham',
        popularity: 0.828,
        profile_path: null,
        cast_id: 71,
        character: '(uncredited)',
        credit_id: '539d41e5c3a3683b23002ce1',
        order: 51,
      },
      {
        adult: false,
        gender: 1,
        id: 1330815,
        known_for_department: 'Acting',
        name: 'Irena Marr',
        original_name: 'Irena Marr',
        popularity: 0.6,
        profile_path: null,
        cast_id: 72,
        character: 'Russian Scientist (uncredited)',
        credit_id: '539d41f9c3a3683b50002b54',
        order: 52,
      },
      {
        adult: false,
        gender: 1,
        id: 1330816,
        known_for_department: 'Acting',
        name: 'Krystyna Marr',
        original_name: 'Krystyna Marr',
        popularity: 0.6,
        profile_path: null,
        cast_id: 73,
        character: 'Russian Scientist (uncredited)',
        credit_id: '539d420bc3a3683b23002d11',
        order: 53,
      },
      {
        adult: false,
        gender: 0,
        id: 1330817,
        known_for_department: 'Acting',
        name: 'Kim Neil',
        original_name: 'Kim Neil',
        popularity: 0.6,
        profile_path: null,
        cast_id: 74,
        character: '(uncredited)',
        credit_id: '539d421ec3a3683b59002b72',
        order: 54,
      },
      {
        adult: false,
        gender: 1,
        id: 1330818,
        known_for_department: 'Acting',
        name: 'Jane Pearl',
        original_name: 'Jane Pearl',
        popularity: 0.98,
        profile_path: null,
        cast_id: 75,
        character: '(uncredited)',
        credit_id: '539d4230c3a3683b37002c2f',
        order: 55,
      },
      {
        adult: false,
        gender: 0,
        id: 1330819,
        known_for_department: 'Acting',
        name: 'Penny Pearl',
        original_name: 'Penny Pearl',
        popularity: 0.6,
        profile_path: null,
        cast_id: 76,
        character: '(uncredited)',
        credit_id: '539d4244c3a3683b48002b19',
        order: 56,
      },
      {
        adult: false,
        gender: 2,
        id: 184980,
        known_for_department: 'Acting',
        name: 'Burnell Tucker',
        original_name: 'Burnell Tucker',
        popularity: 7.291,
        profile_path: '/kSMCUUbt6pplhEKSR3uX8rJDXOy.jpg',
        cast_id: 79,
        character: 'TMA-1 Site Photographer (uncredited)',
        credit_id: '539d43ea0e0a261328003623',
        order: 57,
      },
      {
        adult: false,
        gender: 2,
        id: 1330821,
        known_for_department: 'Acting',
        name: 'John Swindells',
        original_name: 'John Swindells',
        popularity: 0.6,
        profile_path: null,
        cast_id: 78,
        character: 'TMA-1 Site Technician #1 (uncredited)',
        credit_id: '539d42bfc3a3683b23002d3e',
        order: 58,
      },
      {
        adult: false,
        gender: 2,
        id: 1208787,
        known_for_department: 'Acting',
        name: 'John Clifford',
        original_name: 'John Clifford',
        popularity: 0.6,
        profile_path: null,
        cast_id: 81,
        character: 'TMA-1 Site Technician #2 (uncredited)',
        credit_id: '57a3958d9251410c7d00377f',
        order: 59,
      },
      {
        adult: false,
        gender: 2,
        id: 240,
        known_for_department: 'Directing',
        name: 'Stanley Kubrick',
        original_name: 'Stanley Kubrick',
        popularity: 13.634,
        profile_path: '/exfQ6vXXq7rMS5YWb3B88PK39a1.jpg',
        cast_id: 99,
        character: '(voice) (uncredited)',
        credit_id: '63d005060d2f5301d9a5cfc9',
        order: 60,
      },
      {
        adult: false,
        gender: 2,
        id: 1213385,
        known_for_department: 'Acting',
        name: 'Anthony Jackson',
        original_name: 'Anthony Jackson',
        popularity: 0.84,
        profile_path: null,
        cast_id: 102,
        character: 'Ape',
        credit_id: '63fdb9679f1be700e676ee0d',
        order: 61,
      },
    ],
    crew: [
      {
        adult: false,
        gender: 2,
        id: 240,
        known_for_department: 'Directing',
        name: 'Stanley Kubrick',
        original_name: 'Stanley Kubrick',
        popularity: 13.634,
        profile_path: '/exfQ6vXXq7rMS5YWb3B88PK39a1.jpg',
        credit_id: '52fe4212c3a36847f8001a0b',
        department: 'Writing',
        job: 'Screenplay',
      },
      {
        adult: false,
        gender: 2,
        id: 240,
        known_for_department: 'Directing',
        name: 'Stanley Kubrick',
        original_name: 'Stanley Kubrick',
        popularity: 13.634,
        profile_path: '/exfQ6vXXq7rMS5YWb3B88PK39a1.jpg',
        credit_id: '5e8354893344c600182bbb4d',
        department: 'Directing',
        job: 'Director',
      },
      {
        adult: false,
        gender: 2,
        id: 240,
        known_for_department: 'Directing',
        name: 'Stanley Kubrick',
        original_name: 'Stanley Kubrick',
        popularity: 13.634,
        profile_path: '/exfQ6vXXq7rMS5YWb3B88PK39a1.jpg',
        credit_id: '52fe4212c3a36847f8001a05',
        department: 'Production',
        job: 'Producer',
      },
      {
        adult: false,
        gender: 2,
        id: 240,
        known_for_department: 'Directing',
        name: 'Stanley Kubrick',
        original_name: 'Stanley Kubrick',
        popularity: 13.634,
        profile_path: '/exfQ6vXXq7rMS5YWb3B88PK39a1.jpg',
        credit_id: '5a874c109251410aae03fdf4',
        department: 'Visual Effects',
        job: 'Visual Effects',
      },
      {
        adult: false,
        gender: 2,
        id: 243,
        known_for_department: 'Camera',
        name: 'Geoffrey Unsworth',
        original_name: 'Geoffrey Unsworth',
        popularity: 3.689,
        profile_path: '/tlwlMCCVMWnxnOnaWITT61A41PB.jpg',
        credit_id: '52fe4212c3a36847f8001a11',
        department: 'Camera',
        job: 'Director of Photography',
      },
      {
        adult: false,
        gender: 2,
        id: 244,
        known_for_department: 'Editing',
        name: 'Ray Lovejoy',
        original_name: 'Ray Lovejoy',
        popularity: 0.6,
        profile_path: null,
        credit_id: '52fe4212c3a36847f8001a17',
        department: 'Editing',
        job: 'Editor',
      },
      {
        adult: false,
        gender: 0,
        id: 254,
        known_for_department: 'Sound',
        name: 'H.L. Bird',
        original_name: 'H.L. Bird',
        popularity: 0.6,
        profile_path: null,
        credit_id: '52fe4212c3a36847f8001a41',
        department: 'Sound',
        job: 'Sound mixer',
      },
      {
        adult: false,
        gender: 0,
        id: 255,
        known_for_department: 'Sound',
        name: 'Winston Ryder',
        original_name: 'Winston Ryder',
        popularity: 0.699,
        profile_path: null,
        credit_id: '52fe4212c3a36847f8001a47',
        department: 'Sound',
        job: 'Sound Editor',
      },
      {
        adult: false,
        gender: 2,
        id: 241,
        known_for_department: 'Writing',
        name: 'Arthur C. Clarke',
        original_name: 'Arthur C. Clarke',
        popularity: 1.551,
        profile_path: '/bOjZzoPmcdQN0JbGAeVYQd1MUKY.jpg',
        credit_id: '52fe4212c3a36847f8001a53',
        department: 'Writing',
        job: 'Screenplay',
      },
      {
        adult: false,
        gender: 2,
        id: 241,
        known_for_department: 'Writing',
        name: 'Arthur C. Clarke',
        original_name: 'Arthur C. Clarke',
        popularity: 1.551,
        profile_path: '/bOjZzoPmcdQN0JbGAeVYQd1MUKY.jpg',
        credit_id: '52fe4212c3a36847f8001a4d',
        department: 'Writing',
        job: 'Novel',
      },
      {
        adult: false,
        gender: 0,
        id: 257,
        known_for_department: 'Production',
        name: 'Victor Lyndon',
        original_name: 'Victor Lyndon',
        popularity: 0.766,
        profile_path: null,
        credit_id: '52fe4212c3a36847f8001a59',
        department: 'Production',
        job: 'Producer',
      },
      {
        adult: false,
        gender: 2,
        id: 2286,
        known_for_department: 'Camera',
        name: 'John Alcott',
        original_name: 'John Alcott',
        popularity: 2.132,
        profile_path: '/bE05De5gAuLK0xncLNyPq6AmiiQ.jpg',
        credit_id: '5ecd3afd021cee00208a663e',
        department: 'Camera',
        job: 'Additional Photography',
      },
      {
        adult: false,
        gender: 2,
        id: 2288,
        known_for_department: 'Production',
        name: 'James Liggat',
        original_name: 'James Liggat',
        popularity: 0.838,
        profile_path: null,
        credit_id: '53918926c3a3685ed9000f92',
        department: 'Production',
        job: 'Casting',
      },
      {
        adult: false,
        gender: 0,
        id: 9402,
        known_for_department: 'Crew',
        name: 'Brian Johnson',
        original_name: 'Brian Johnson',
        popularity: 0.6,
        profile_path: null,
        credit_id: '52fe4212c3a36847f8001a5f',
        department: 'Crew',
        job: 'Special Effects',
      },
      {
        adult: false,
        gender: 2,
        id: 11837,
        known_for_department: 'Costume & Make-Up',
        name: 'Stuart Freeborn',
        original_name: 'Stuart Freeborn',
        popularity: 0.98,
        profile_path: null,
        credit_id: '5a7a35260e0a26598802fd5b',
        department: 'Costume & Make-Up',
        job: 'Makeup Artist',
      },
      {
        adult: false,
        gender: 2,
        id: 12112,
        known_for_department: 'Visual Effects',
        name: 'Douglas Trumbull',
        original_name: 'Douglas Trumbull',
        popularity: 1.243,
        profile_path: '/wVDG2FBqenOpVwNUySqhXfBjifr.jpg',
        credit_id: '5a874c1a0e0a2652ab040c36',
        department: 'Visual Effects',
        job: 'Visual Effects',
      },
      {
        adult: false,
        gender: 2,
        id: 12510,
        known_for_department: 'Art',
        name: 'Anthony Masters',
        original_name: 'Anthony Masters',
        popularity: 0.6,
        profile_path: '/32OGKBShuM420L7FxP1XfXfjqBz.jpg',
        credit_id: '53918978c3a36864910010f1',
        department: 'Art',
        job: 'Production Design',
      },
      {
        adult: false,
        gender: 0,
        id: 18758,
        known_for_department: 'Crew',
        name: 'Les Bowie',
        original_name: 'Les Bowie',
        popularity: 1.4,
        profile_path: null,
        credit_id: '52fe4212c3a36847f8001a65',
        department: 'Crew',
        job: 'Special Effects',
      },
      {
        adult: false,
        gender: 2,
        id: 26872,
        known_for_department: 'Art',
        name: 'Robert Cartwright',
        original_name: 'Robert Cartwright',
        popularity: 0.6,
        profile_path: null,
        credit_id: '53918a12c3a3685ed9000fa3',
        department: 'Art',
        job: 'Set Decoration',
      },
      {
        adult: false,
        gender: 2,
        id: 957776,
        known_for_department: 'Art',
        name: 'John Hoesli',
        original_name: 'John Hoesli',
        popularity: 1.539,
        profile_path: null,
        credit_id: '539189dac3a36864630011d5',
        department: 'Art',
        job: 'Art Direction',
      },
      {
        adult: false,
        gender: 2,
        id: 960844,
        known_for_department: 'Sound',
        name: 'A.W. Watkins',
        original_name: 'A.W. Watkins',
        popularity: 0.6,
        profile_path: null,
        credit_id: '63f595e88c22c0007c7e8745',
        department: 'Sound',
        job: 'Sound Supervisor',
      },
      {
        adult: false,
        gender: 2,
        id: 986346,
        known_for_department: 'Art',
        name: 'Ernest Archer',
        original_name: 'Ernest Archer',
        popularity: 0.6,
        profile_path: null,
        credit_id: '53918945c3a3686488001100',
        department: 'Art',
        job: 'Production Design',
      },
      {
        adult: false,
        gender: 0,
        id: 1125548,
        known_for_department: 'Art',
        name: 'Harry Lange',
        original_name: 'Harry Lange',
        popularity: 0.6,
        profile_path: null,
        credit_id: '53918958c3a36864630011ca',
        department: 'Art',
        job: 'Production Design',
      },
      {
        adult: false,
        gender: 2,
        id: 1221897,
        known_for_department: 'Acting',
        name: 'Bobby Clark',
        original_name: 'Bobby Clark',
        popularity: 0.94,
        profile_path: null,
        credit_id: '5d8f2c66172d7f001f560cc3',
        department: 'Crew',
        job: 'Stunts',
      },
      {
        adult: false,
        gender: 2,
        id: 1390333,
        known_for_department: 'Art',
        name: 'Dick Frift',
        original_name: 'Dick Frift',
        popularity: 0.6,
        profile_path: null,
        credit_id: '54783c349251416a27000172',
        department: 'Art',
        job: 'Construction Coordinator',
      },
      {
        adult: false,
        gender: 2,
        id: 1513635,
        known_for_department: 'Directing',
        name: 'Derek Cracknell',
        original_name: 'Derek Cracknell',
        popularity: 2.544,
        profile_path: null,
        credit_id: '63f59565fc31d30089c9b26b',
        department: 'Directing',
        job: 'First Assistant Director',
      },
      {
        adult: false,
        gender: 2,
        id: 1556557,
        known_for_department: 'Camera',
        name: 'Kelvin Pike',
        original_name: 'Kelvin Pike',
        popularity: 0.6,
        profile_path: null,
        credit_id: '5ecd3b67021cee00228ac160',
        department: 'Camera',
        job: 'Camera Operator',
      },
      {
        adult: false,
        gender: 0,
        id: 1973867,
        known_for_department: 'Costume & Make-Up',
        name: 'Graham Freeborn',
        original_name: 'Graham Freeborn',
        popularity: 0.6,
        profile_path: null,
        credit_id: '5a7a353bc3a368227302e9fe',
        department: 'Costume & Make-Up',
        job: 'Makeup Artist',
      },
      {
        adult: false,
        gender: 2,
        id: 1973868,
        known_for_department: 'Sound',
        name: 'Malcolm Stewart',
        original_name: 'Malcolm Stewart',
        popularity: 0.6,
        profile_path: null,
        credit_id: '5a7a35690e0a265985030236',
        department: 'Sound',
        job: 'Sound Designer',
      },
      {
        adult: false,
        gender: 2,
        id: 2227681,
        known_for_department: 'Camera',
        name: 'David Wynn-Jones',
        original_name: 'David Wynn-Jones',
        popularity: 2.835,
        profile_path: null,
        credit_id: '5c5d914c0e0a261de167d1d2',
        department: 'Camera',
        job: 'Clapper Loader',
      },
      {
        adult: false,
        gender: 1,
        id: 2231114,
        known_for_department: 'Costume & Make-Up',
        name: 'Mary Gibson',
        original_name: 'Mary Gibson',
        popularity: 0.6,
        profile_path: null,
        credit_id: '5c5a81789251413374b7c22b',
        department: 'Costume & Make-Up',
        job: 'Wardrobe Supervisor',
      },
      {
        adult: false,
        gender: 0,
        id: 2420363,
        known_for_department: 'Crew',
        name: 'John Francis',
        original_name: 'John Francis',
        popularity: 0.6,
        profile_path: null,
        credit_id: '5d8f2cb5109cd00019420139',
        department: 'Crew',
        job: 'Stunt Coordinator',
      },
      {
        adult: false,
        gender: 0,
        id: 2654892,
        known_for_department: 'Camera',
        name: 'George Watts',
        original_name: 'George Watts',
        popularity: 0.6,
        profile_path: null,
        credit_id: '5ecd3b4f1da7a6001ccfcc1f',
        department: 'Camera',
        job: 'Assistant Camera',
      },
      {
        adult: false,
        gender: 0,
        id: 3068555,
        known_for_department: 'Editing',
        name: 'David de Wilde',
        original_name: 'David de Wilde',
        popularity: 0.6,
        profile_path: null,
        credit_id: '627288bd6f53e158ec248385',
        department: 'Crew',
        job: 'Editorial Staff',
      },
    ],
  },
};
