name: Tests
run-name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Post Coverage
        uses: coverallsapp/github-action@v2
